version: '2'

services:
  ftpserver:
    image: dockers.ikuai8.com/bigdata/ftpserver:1.0.0
    container_name: ftpserver
    ports:
     - "20-21:20-21"
     - "59900-60000:59900-60000"
    environment:
     - PASV_MIN_PORT=59900
     - PASV_MAX_PORT=60000
     - PASV_ADDRESS=
     - IF_TEST_FTP=NO
    volumes:
     - /ikuai/bigdata/ftpserver/data:/home/ftpserver
     - /ikuai/bigdata/ftpserver/config:/etc/vsftpd/data
     - /ikuai/log/ftpserver:/var/log/vsftpd
     - /etc/localtime:/etc/localtime:ro
    networks:
      -  bigdata_network
    restart: on-failure
 

networks:
  bigdata_network:
    external: true
    
